CREATE TABLE IF NOT EXISTS accounts(
	id	UUID	NOT NULL PRIMARY KEY,
	username	VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL,
	firstname VARCHAR(100) NOT NULL,
	lastname VARCHAR(100) NOT NULL
);